name: Run Selenium Tests with Allure and Publish Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests and generate Allure report
        run: ./gradlew clean test allureReport
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

      - name: List contents of Allure report folder
        run: ls -R build/reports/allure-report/allureReport || echo "❌ Report not found"

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/allure-report/allureReport
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com